site:
  title: Antora Example multiple-components/xrefs
  url: http://example.com
  start_page: v1@component1::index.adoc
content:
  sources:
  - url: ./../../
    start_path: multiple-components/xrefs/component1/version1
  - url: ./../../
    start_path: multiple-components/xrefs/component1/version2
  - url: ./../../
    start_path: multiple-components/xrefs/component1/version3
  - url: ./../../
    start_path: multiple-components/xrefs/component2/version1
  - url: ./../../
    start_path: multiple-components/xrefs/component2/version2
  - url: ./../../
    start_path: multiple-components/xrefs/component2/version3
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true