= Simple Examples

This repository contains simple examples of Antora projects showing single features in isolation. They all use the Antora Default UI.

== Beware

In order to demonstrate many features in minimal space, all these projects employ a compressed layout. This works, but is unsuitable for any but the smallest projects.  For any real project, at least the playbook project and the content should be in separate git repositories.

== Prerequisites

You must have Antora installed, preferably globally.

Clone this repo locally.

== Usage

* cd `example-directory`
* antora antora-playbook.yml
* Examine the results in build/

== Contributing

* An easy starting point is to use the antora-schematics example schematic to set up your Antora example with the components it needs. The schematic will create the path, put the antora-playbook.yml file there, and put the components there.
* Name the directory to clearly describe the examples purpose.
* Use the pages of the example to clearly describe the effects of the demonstrated configuration.

```
antora-schematics example --gitPath=- --path=<path-to-example> --components=<comma-separated list of component paths> [gitAuthor=<git Author> gitEmail=<gitEmail>]
```

All new files should be added; if you specify gitAuthor and gitEmail they should also be committed.
