= Simple Examples

This repository contains simple examples of Antora projects showing single features in isolation. They all use the Antora Default UI.

== Beware

In order to demonstrate many features in minimal space, all these projects employ a compressed layout. This works, but is unsuitable for any but the smallest projects.  For any real project, at least the playbook project and the content should be in separate git repositories.

== Prerequisites

You must have Antora installed, preferably globally.

Clone this repo locally.

== Usage

* cd `example-directory`
* antora antora-playbook.yml
* Examine the results in build/

== Contributing

* An easy starting point is to use the antora-schematics example schematic to set up your Antora example with the components it needs. The schematic will create the path, put the antora-playbook.yml file there, and put the components there.
* Name the directory to clearly describe the examples purpose.
* Use the pages of the example to clearly describe the effects of the demonstrated configuration.

```
antora-schematics example --gitPath=- --path=<path-to-example> --components=<comma-separated list of component paths> [authorName=<git Author> authorEmail=<gitEmail>]
```

All new files should be added; if you specify gitAuthor and gitEmail they should also be committed.

== To build everything:

----
find . -name antora-playbook.yml|xargs -n 1 bash -c 'for filename; do (cd `dirname "$filename"`; antora antora-playbook.yml); done' bash 
----

== To clean
----
find . -name build |xargs rm -rf
----

=== Catalog

The links will only work locally if you view this page in an asciidoc enabled browser, after building all the projects.

* simplest: minimal example that produces a site with content and navigation link:simplest/build/site/SimplestComponent/1.0/index.html[]. Note there is no site start_page.
//* tiny: adds a site start page, site.xml, robots.txt
* One component:
** Including hidden files whose names start with '_' underscore link:one-components/underscore-include/build/site/UnderscoreInclude/1.0/index.html[]
** Including the same content in multiple nav positions or flows using include stubs link:one-components/multiple-uses/build/site/index.html[]
* Multiple components: multiple-components
** Two components link:multiple-components/two-components/build/site/Component1/1.0/index.html[]
** Links between two components link:multiple-components/links-between-components/build/site/index.html[]
* Distributed components: distributed-components
** One component, two source trees link:distributed-components/simple-distributed/build/site/index.html[]. (site start_page)
