= {page-component-title}

== asciidoctor-mathjax extension examples in Antora

This example shows different ways of using the asciidoctor-mathjax.js extension in Antora.

xref:stem-asciimath.adoc[Asciimath (default) format using '`stem`' notation]

xref:stem-latexmath.adoc[Latexmath format using '`stem`' notation]

xref:asciimath.adoc[Asciimath using '`asciimath`' notation]

xref:latexmath.adoc[Latexmath using '`latexmath`' notation]

xref:mixed.adoc[Using both asciimath and latexmath on the same page]

xref:inclusions.adoc[Including pages with stem content]

xref:tables.adoc[Stem content in asciidoc table cells]

== Installation and usage

The simplest way to install this extension is to add a package.json file to your Antora doc project, next to the playbook.

Here is a minimal example:

[source,json]
{
  "devDependencies": {
    "@djencks/asciidoctor-mathjax": "^0.0.5"
  }
}

This example also installs Antora and provides a build sript:

[source,json]
{
  "private": true,
  "scripts": {
    "build": "node_modules/.bin/antora antora-playbook.yml --fetch --stacktrace"
  },
  "devDependencies": {
    "@antora/cli": "^2.2.0"
    "@antora/site-generator-default": "^2.2.0"
    "@djencks/asciidoctor-mathjax": "^0.0.5"
  }
}

With either of these, the dependencies will be installed by running `npm i`.
With the second, your project may be built by running `npm run build`

To configure use of this asciidoctor extension in your project, mention it in your playbook:

[source,yml]
----
asciidoc:
  extensions:
  - "@djencks/asciidoctor-mathjax"
----


=== Building this example Antora doc project

After installing the extension, you can build the site with

```
antora antora-playbook.yml
```
