= {description}
:description: indexDescriptionList Examples

== Page Coordinates


page-component-name: component

page-component-version: 1.0

page-module: ROOT

page-relative: {page-relative}

== Examples of `indexDescriptionList` block macro

All `indexDescriptionList` uses specify `style=horizontal`.
Whether it has an effect depends on whether the use creates a new dlist or appends to an existing one.

First, a plain description list:

[source,adoc]
indexDescriptionList::[descAttribute=description,style=horizontal]

indexDescriptionList::[descAttribute=description,style=horizontal]

Next we expect a list:

[source,adoc]
----
This is a dlist item:: First!

indexDescriptionList::[level=1,descAttribute=description,style=horizontal]
----

This is a dlist item:: First!
Next is level 1

indexDescriptionList::[level=1,descAttribute=description,style=horizontal]

This is a dlist item:: Second!
This is a sub item::: Sub1!
Third level A:::: SubSub1!
Next is level 1

indexDescriptionList::[level=1,descAttribute=description,style=horizontal]

This is a dlist item:: Third!
This is a sub item::: Sub1!
Third level B:::: SubSub1!
Next is level 2

indexDescriptionList::[level=2,descAttribute=description,style=horizontal]

This is a dlist item:: Fourth!
This is a sub item::: Sub1!
Third level C:::: SubSub1!
Next is level 3

indexDescriptionList::[level=3,descAttribute=description,style=horizontal]

This is a dlist item:: Fifth!
This is a sub item::: Sub1!
Third level D:::: SubSub1!
Next is level 4 (which doesn't work well using .adoc source)

indexDescriptionList::[level=4,descAttribute=description,style=horizontal]

this is not a list item

next should be:: separate (no level)

indexDescriptionList::[module=module1,descAttribute=doctitle,style=horizontal]

next has relative filter (no level)

indexDescriptionList::[component=*,version=*,module=*,relative=topic*/*.adoc,descAttribute=description,style=horizontal]

