= {description}
:description: The asciidoctor-antora-indexer Extension

== Purpose

The `@djencks/asciidoctor-antora-indexer` asciidoctor extension queries the "database" of the Antora content catalog.
The results of the query are a set of pages, which are then sorted by lower-cased doctitle.
This list of pages is then presented as a list, a description list, or a table, or a repeating template block or aggregated to a count.

The query can match the Antora page coordinates and the header attributes of the page.

== Examples

The examples are organized by the macros used.

=== indexList

The selected pages are presented as a unordered list.
The nesting level of the list may be specified.
The macro takes account of preceding lists and inserts the generated list at the appropriate nesting level after the preceding list item.

xref:list.adoc[]

=== indexOrderedList

The selected pages are presented as a ordered list.
The nesting level of the list may be specified.
The macro takes account of preceding lists and inserts the generated list at the appropriate nesting level after the preceding list item.

xref:ordered-list.adoc[]

=== indexDescriptionList

The selected pages are presented as a description list.
The nesting level of the list may be specified.
The macro takes account of preceding lists and inserts the generated list at the appropriate nesting level after the preceding list item.
The term is the xref to the target page, and the description is taken from a specified attribute.

xref:description-list.adoc[]

=== Mixed list types

This page presents a few examples of mixing list types and index macros.

xref:mixed-list.adoc[]

=== indexTable

The selected pages are presented as a table.
The attributes mapped to the columns of the table are specified in the macro.
This relies on an immediately preceding table to set up the column structure and headers.

xref:table.adoc[]

=== indexCount and indexUniqueCount

For indexCount, the selected pages are counted.
For indexUniqueCount, the number of unique values of a specified attribute are counted.

xref:count.adoc[]

=== indexBlock

The indicated block is used as a template for each selected page, with the specified attributes or expressions supplied as attributes to the template.

xref:block.adoc[]
