site:
  title: Antora Example distributed-components/module-per-source
  url: http://example.com
  start_page: component1::index.adoc

content:
  sources:
  - url: ./../../
    start_paths:
    - distributed-components/module-per-source/module1-source
    - distributed-components/module-per-source/root-source
    - distributed-components/module-per-source/module2-3-source

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  clean: true
